name: Update Newsbrief Playlist
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # twice an hour at :12 and :42
    - cron:  '12,42 * * * *'
jobs:
  update:
    name: Update News Brief playlist
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t newsbrief-updater .
      - name: Run script
        run: docker run -e SPOTIFY_CLIENT_ID="$SPOTIFY_CLIENT_ID" -e SPOTIFY_CLIENT_SECRET="$SPOTIFY_CLIENT_SECRET" -e MONGO_USERNAME="$MONGO_USERNAME" -e MONGO_PASSWORD="$MONGO_PASSWORD" newsbrief-updater
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}