name: Update Newsbrief Playlist
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # 8am on the 10th of every month
    - cron:  '0 1,3,5,13,14,17,20,23 * * *'
jobs:
  update:
    name: Update News Brief playlist
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t newsbrief-updater .
      - name: Run script
        run: docker run newsbrief-updater
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}